window.PACK_IMPORTS = window.PACK_IMPORTS || {};
window.PACK_IMPORTS.japan = {
  topicName: "Japan",
  topicKey: "japan",
  tasks: [
    "[Documents] Passport + waiver + cards — 1 set · Keep in backpack",
    "[Clothes] T-shirts/tops — 4–5 · Lightweight quick-dry",
    "[Clothes] Long pants — 2 · Wear 1 on flight",
    "[Clothes] Shorts — 1 · Optional",
    "[Clothes] Underwear — 5–6 · Do laundry once",
    "[Clothes] Socks — 5–6 pairs · Thin socks",
    "[Clothes] Sleepwear — 1 · Light material",
    "[Clothes] Thin jacket — 1 · Wear on plane, not luggage",
    "[Clothes] Walking shoes — 1 pair · Wear, don't pack",
    "[Clothes] Sandals/slippers — Skip if possible · Saves space/weight",
    "[Weather] Compact umbrella — 1 · Small foldable",
    "[Weather] Portable fan — 1 · USB rechargeable",
    "[Weather] Cap/hat — 1 · Wear during travel",
    "[Toiletries] Toothbrush/toothpaste — 1 · Travel size only",
    "[Toiletries] Deodorant — 1 · Small stick/spray",
    "[Toiletries] Sunscreen — 1 · ≤100ml",
    "[Toiletries] Skincare — Minimal · Decant into mini bottles",
    "[Toiletries] Wet wipes — 1 small pack",
    "[Medicine] Personal meds — Small pack · Essential only",
    "[Medicine] Paracetamol — Few tablets",
    "[Medicine] Diarrhea medicine — Few tablets",
    "[Medicine] Band-aids — Few",
    "[Tech] Phone — 1 · On body",
    "[Tech] Charger — 1 · Fast charger shared if possible",
    "[Tech] Power bank — 1 · Keep in backpack",
    "[Tech] Universal adapter — 1 shared · Share between 2 people",
    "[Tech] Earphones — 1",
    "[Flight Items] Reusable water bottle — 1 · Empty before security",
    "[Flight Items] Snacks — Few · Light only",
    "[Bags] Cabin luggage — 1 · Target: 5.5–6.5kg packed",
    "[Bags] Backpack/day bag — 1 · Put heavy items here",
    "[Optional] Foldable tote bag — 1 · For shopping later",
    "[Optional] Laundry bag — 1 · Very light"
  ]
};
